/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PredictionMarketInterface extends Interface {
  functions: {
    allowedToBuy: TypedFunctionDescription<{ encode([]: []): string }>;

    buy: TypedFunctionDescription<{ encode([]: []): string }>;

    getBalance: TypedFunctionDescription<{ encode([addr]: [string]): string }>;

    getChallengeBlock: TypedFunctionDescription<{ encode([]: []): string }>;

    getCurrentPrice: TypedFunctionDescription<{ encode([]: []): string }>;

    getExpirationBlock: TypedFunctionDescription<{ encode([]: []): string }>;

    niftyDollarAddr: TypedFunctionDescription<{ encode([]: []): string }>;

    predictPriceDown: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;

    predictPriceUp: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;

    withdraw: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {
    PredictPriceDown: TypedEventDescription<{
      encodeTopics([predictor, amount, assetPrice]: [
        string | null,
        null,
        null
      ]): string[];
    }>;

    PredictPriceUp: TypedEventDescription<{
      encodeTopics([predictor, amount, assetPrice]: [
        string | null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class PredictionMarket extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PredictionMarket;
  attach(addressOrName: string): PredictionMarket;
  deployed(): Promise<PredictionMarket>;

  on(event: EventFilter | string, listener: Listener): PredictionMarket;
  once(event: EventFilter | string, listener: Listener): PredictionMarket;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PredictionMarket;
  removeAllListeners(eventName: EventFilter | string): PredictionMarket;
  removeListener(eventName: any, listener: Listener): PredictionMarket;

  interface: PredictionMarketInterface;

  functions: {
    allowedToBuy(): Promise<boolean>;

    buy(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    getBalance(addr: string): Promise<BigNumber>;

    getChallengeBlock(): Promise<BigNumber>;

    getCurrentPrice(): Promise<BigNumber>;

    getExpirationBlock(): Promise<BigNumber>;

    niftyDollarAddr(): Promise<string>;

    predictPriceDown(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    predictPriceUp(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdraw(overrides?: TransactionOverrides): Promise<ContractTransaction>;
  };

  allowedToBuy(): Promise<boolean>;

  buy(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  getBalance(addr: string): Promise<BigNumber>;

  getChallengeBlock(): Promise<BigNumber>;

  getCurrentPrice(): Promise<BigNumber>;

  getExpirationBlock(): Promise<BigNumber>;

  niftyDollarAddr(): Promise<string>;

  predictPriceDown(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  predictPriceUp(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  withdraw(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  filters: {
    PredictPriceDown(
      predictor: string | null,
      amount: null,
      assetPrice: null
    ): EventFilter;

    PredictPriceUp(
      predictor: string | null,
      amount: null,
      assetPrice: null
    ): EventFilter;
  };

  estimate: {
    allowedToBuy(): Promise<BigNumber>;

    buy(): Promise<BigNumber>;

    getBalance(addr: string): Promise<BigNumber>;

    getChallengeBlock(): Promise<BigNumber>;

    getCurrentPrice(): Promise<BigNumber>;

    getExpirationBlock(): Promise<BigNumber>;

    niftyDollarAddr(): Promise<BigNumber>;

    predictPriceDown(_amount: BigNumberish): Promise<BigNumber>;

    predictPriceUp(_amount: BigNumberish): Promise<BigNumber>;

    withdraw(): Promise<BigNumber>;
  };
}
